/**
 * The map — the app as three places on a route.
 *
 * The board art was generated by GlianaAI itself (krea-2-medium-turbo, through
 * the gateway this app pays) — the product decorating the product.
 *
 * The buildings in the art ARE the destinations, so the nodes are transparent
 * hit areas over them rather than boxes drawn on top: a drawn box fights the
 * art it sits on. They are still real Pressables, because a target has to be
 * 44px and press like a button.
 *
 * Only the Arena node carries live state — a lit ring, a green dot, the
 * countdown — because it is the only place with a deadline.
 */
import { StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { Image } from 'expo-image';
import { colors, font, space } from '../theme';
import { Press } from './arena/bits';

export interface MapNode {
  id: string;
  label: string;
  glyph: string;
  /** Position as a fraction of the board, 0–1. */
  x: number;
  y: number;
  /** One live line under the label, when the node has something to say. */
  status?: string;
  live?: boolean;
  onPress: () => void;
}

/** The art is 1100x614; the board keeps that ratio so buildings stay under nodes. */
const RATIO = 1100 / 614;
const NODE = 80;

export function MapBoard({ nodes }: { nodes: MapNode[] }) {
  const { width } = useWindowDimensions();
  const boardWidth = width - space(5) * 2;
  const boardHeight = boardWidth / RATIO;
  const at = (n: MapNode) => ({ x: n.x * boardWidth, y: n.y * boardHeight });

  return (
    <View style={[styles.board, { height: boardHeight }]}>
      <Image
        source={require('../../assets/map-board.png')}
        style={StyleSheet.absoluteFill}
        contentFit="cover"
      />

      {nodes.map((n) => {
        const p = at(n);
        return (
          <Press
            key={n.id}
            onPress={n.onPress}
            haptic="none"
            style={[styles.node, { left: p.x - NODE / 2, top: p.y - NODE / 2 }, n.live && styles.nodeLive]}
          >
            {n.live ? <View style={styles.dot} /> : null}
          </Press>
        );
      })}

      {nodes.map((n) => {
        const p = at(n);
        return (
          <View
            key={`${n.id}-label`}
            style={[styles.labelWrap, { left: p.x - 80, top: p.y + NODE / 2 - 2 }]}
            pointerEvents="none"
          >
            <Text style={styles.label}>{n.label}</Text>
            {n.status ? <Text style={styles.status}>{n.status}</Text> : null}
          </View>
        );
      })}
    </View>
  );
}

const styles = StyleSheet.create({
  board: {
    marginTop: space(5),
    marginBottom: space(4),
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  // Transparent over the building it covers: the art is the button's face.
  node: { position: 'absolute', width: NODE, height: NODE, borderRadius: 4 },
  nodeLive: { borderWidth: 2, borderColor: colors.flame, backgroundColor: 'rgba(245,158,11,0.10)' },
  dot: { position: 'absolute', top: 4, right: 4, width: 8, height: 8, backgroundColor: colors.green },
  labelWrap: { position: 'absolute', width: 160, alignItems: 'center' },
  // Hard shadows, so a label stays readable wherever the art is bright.
  label: {
    color: colors.text,
    fontSize: 8,
    fontFamily: font.pixel,
    letterSpacing: 1,
    textShadowColor: '#000',
    textShadowRadius: 4,
  },
  status: { color: colors.text, fontSize: 11, marginTop: 4, textShadowColor: '#000', textShadowRadius: 4 },
});
