/**
 * The map — the app as three places on a route.
 *
 * The board art was generated by GlianaAI itself (krea-2-medium-turbo, through
 * the gateway this app pays) — the product decorating the product.
 *
 * The buildings in the art ARE the destinations, so the nodes are transparent
 * hit areas over them rather than boxes drawn on top: a drawn box fights the
 * art it sits on. They are still real Pressables, because a target has to be
 * 44px and press like a button.
 *
 * Only the Arena node carries live state — a lit ring, a green dot, the
 * countdown — because it is the only place with a deadline.
 *
 * Travel is a TAP GESTURE racing the pan, not a Pressable per building.
 *
 * Pressables nested inside a panning, transformed view are fragile: the pan
 * claims the touch, and any finger that drifts a few pixels cancels the press.
 * Both failures look identical to the user — the building does nothing. One tap
 * gesture on the board, hit-testing the buildings itself in board coordinates,
 * has neither problem and gives every node the same generous 24px slop.
 *
 * The board is BIGGER than the screen and you drag it around. A map you cannot
 * move is a picture; the whole point of an overworld is that there is more of
 * it than you can see. Panning runs on the UI thread through a shared value, so
 * React never re-renders while your finger is down, and the edges rubber-band
 * rather than stopping dead.
 */
import { StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Image } from 'expo-image';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import * as Haptics from 'expo-haptics';
import Animated, { useAnimatedStyle, useSharedValue, withSpring } from 'react-native-reanimated';
import { colors, font, space } from '../theme';

export interface MapNode {
  id: string;
  label: string;
  /** Position of the building's CENTRE, as a fraction of the board, 0–1. */
  x: number;
  y: number;
  /**
   * Hit area, as a fraction of board width/height. It should cover the building
   * in the art: a small square floating above the label is a target nobody can
   * find, which is exactly how these nodes shipped unclickable.
   */
  w?: number;
  h?: number;
  /** One live line under the label, when the node has something to say. */
  status?: string;
  live?: boolean;
  onPress: () => void;
}

/**
 * The board is the SCREEN, not a card on it: the art fills the viewport and the
 * nodes sit on the buildings. Portrait art (900x1613) because a phone is
 * portrait, and cover-cropping a landscape map throws away two of its three
 * destinations.
 */
const NODE_W = 0.34;
const NODE_H = 0.12;
/** How much bigger than the viewport the board is drawn — the room to explore. */
const OVERSCAN = 1.35;
/** Art aspect, so the board keeps its proportions at any size. */
const ART_RATIO = 900 / 1613;

export function MapBoard({
  nodes,
  hud,
  footer,
}: {
  nodes: MapNode[];
  /** In-world HUD across the top: the app's chrome, dressed as game furniture. */
  hud?: React.ReactNode;
  footer?: React.ReactNode;
}) {
  const { width, height } = useWindowDimensions();
  const insets = useSafeAreaInsets();

  // The board fills the width and overscans the height, so there is always
  // somewhere to drag to.
  const boardWidth = Math.max(width, height * ART_RATIO) * OVERSCAN;
  const boardHeight = boardWidth / ART_RATIO;
  const maxX = Math.max(0, (boardWidth - width) / 2);
  const maxY = Math.max(0, boardHeight - height);

  const x = useSharedValue(0);
  // Start at the top of the world: the arcade then sits clear of the HUD, and
  // the gallery below the fold is a reason to drag.
  const y = useSharedValue(0);
  const startX = useSharedValue(0);
  const startY = useSharedValue(0);

  const hit = (px: number, py: number) => {
    // Last first: later nodes draw on top, so they should win an overlap.
    for (let i = nodes.length - 1; i >= 0; i--) {
      const b = box(nodes[i]);
      if (px >= b.left && px <= b.left + b.width && py >= b.top && py <= b.top + b.height) return nodes[i];
    }
    return null;
  };

  // runOnJS because the handler calls straight into navigation — there is
  // nothing to animate here, and hopping threads for a tap is wasted ceremony.
  const tap = Gesture.Tap()
    .runOnJS(true)
    .maxDuration(500)
    .maxDistance(24)
    .onEnd((e) => {
      const node = hit(e.x, e.y);
      if (!node) return;
      void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      node.onPress();
    });

  const pan = Gesture.Pan()
    // Without a movement threshold the pan claims every touch the moment it
    // lands, so the buildings stopped being tappable the day the map started
    // moving. 8px is enough to tell a drag from a tap and small enough that a
    // drag still feels immediate.
    .activeOffsetX([-12, 12])
    .activeOffsetY([-12, 12])
    .onBegin(() => {
      startX.set(x.get());
      startY.set(y.get());
    })
    .onUpdate((e) => {
      // Rubber band past the edge: a hard stop feels like a bug, and the
      // resistance is what tells you the map has an edge at all.
      const nx = startX.get() + e.translationX;
      const ny = startY.get() + e.translationY;
      x.set(nx > maxX ? maxX + (nx - maxX) * 0.25 : nx < -maxX ? -maxX + (nx + maxX) * 0.25 : nx);
      y.set(ny > 0 ? ny * 0.25 : ny < -maxY ? -maxY + (ny + maxY) * 0.25 : ny);
    })
    .onEnd((e) => {
      // Velocity carries into the spring, so a flick keeps travelling.
      const settle = { duration: 500, dampingRatio: 0.9 } as const;
      const restX = Math.min(maxX, Math.max(-maxX, x.get() + e.velocityX * 0.08));
      const restY = Math.min(0, Math.max(-maxY, y.get() + e.velocityY * 0.08));
      x.set(withSpring(restX, { ...settle, velocity: e.velocityX }));
      y.set(withSpring(restY, { ...settle, velocity: e.velocityY }));
    });

  const board = useAnimatedStyle(() => ({ transform: [{ translateX: x.get() }, { translateY: y.get() }] }));
  const box = (n: MapNode) => {
    const w = (n.w ?? NODE_W) * boardWidth;
    const h = (n.h ?? NODE_H) * boardHeight;
    return { left: n.x * boardWidth - w / 2, top: n.y * boardHeight - h / 2, width: w, height: h };
  };
  const labelTop = (n: MapNode) => n.y * boardHeight + ((n.h ?? NODE_H) * boardHeight) / 2 - 4;

  return (
    <View style={styles.board}>
      <GestureDetector gesture={Gesture.Race(pan, tap)}>
        <Animated.View style={[{ width: boardWidth, height: boardHeight, left: -(boardWidth - width) / 2 }, board]}>
          <Image source={require('../../assets/map-board.png')} style={StyleSheet.absoluteFill} contentFit="cover" />

          {nodes.map((n) => {
            if (!n.live) return null;
            const b = box(n);
            // A quest pin above the door, which is how a game says "something is
            // happening here". The border box it replaces read as a selection
            // rectangle — an editor's idiom, not a world's.
            return (
              <View key={`${n.id}-pin`} style={[styles.pin, { left: b.left + b.width / 2 - 16, top: b.top - 30 }]} pointerEvents="none">
                <Text style={styles.pinText}>!</Text>
              </View>
            );
          })}

          {nodes.map((n) => {
            return (
              <View
                key={`${n.id}-label`}
                style={[styles.labelWrap, { left: n.x * boardWidth - 90, top: labelTop(n) }]}
                pointerEvents="none"
              >
                <Text style={styles.label}>{n.label}</Text>
                {n.status ? <Text style={styles.status}>{n.status}</Text> : null}
              </View>
            );
          })}
        </Animated.View>
      </GestureDetector>

      {/* Chrome sits ABOVE the moving board, so the HUD stays put while the
          world slides under it. */}
      <View style={styles.scrimTop} pointerEvents="none" />
      <View style={styles.scrimBottom} pointerEvents="none" />
      {hud ? <View style={[styles.hud, { paddingTop: insets.top + space(2) }]}>{hud}</View> : null}
      {footer ? <View style={styles.footer}>{footer}</View> : null}
    </View>
  );
}

const styles = StyleSheet.create({
  board: { flex: 1, backgroundColor: colors.ink, overflow: 'hidden' },
  scrimTop: { position: 'absolute', top: 0, left: 0, right: 0, height: 130, backgroundColor: 'rgba(10,10,13,0.45)' },
  scrimBottom: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 150, backgroundColor: 'rgba(10,10,13,0.35)' },
  hud: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    paddingHorizontal: space(3),
    flexDirection: 'row',
    alignItems: 'center',
    gap: space(2),
  },
  footer: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: space(4), paddingBottom: space(8), gap: space(2) },
  pin: {
    position: 'absolute',
    width: 32,
    height: 28,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: colors.flameDeep,
    backgroundColor: colors.flame,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinText: { color: colors.ink, fontSize: 11, fontFamily: font.pixel },
  labelWrap: { position: 'absolute', width: 180, alignItems: 'center' },
  // Hard shadows, so a label stays readable wherever the art is bright.
  label: {
    color: colors.text,
    fontSize: 9,
    fontFamily: font.pixel,
    letterSpacing: 1,
    textShadowColor: '#000',
    textShadowRadius: 4,
  },
  status: { color: colors.text, fontSize: 11, marginTop: 4, textShadowColor: '#000', textShadowRadius: 4 },
});
