/**
 * Generate the Kit-native TypeScript client from the Anchor IDL.
 *
 * The client is generated, never hand-written: the Solana skill's rule is not to
 * hand-maintain Borsh layouts for a program you own, and a hand-rolled encoder
 * drifts from the program the first time an account gains a field.
 *
 * Output lands in the APP's source tree (src/arena/generated) because the phone
 * app is the only consumer. It emits @solana/kit code only — no web3.js — which
 * is what keeps it out of the React Native bundle.
 */
import { readFileSync, writeFileSync, rmSync, cpSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createFromRoot } from 'codama';
import { rootNodeFromAnchor } from '@codama/nodes-from-anchor';
import { renderVisitor } from '@codama/renderers-js';

const idl = JSON.parse(readFileSync(new URL('../target/idl/arena.json', import.meta.url), 'utf8'));
const out = new URL('../../../src/arena/generated/', import.meta.url).pathname;

// The renderer writes a whole package (package.json, src/generated/...). The app
// only wants the modules, so render to a temp dir and lift src/generated out.
const staging = mkdtempSync(join(tmpdir(), 'arena-codama-'));
// accept() is async here — without the await the copy below runs against an
// empty directory and silently produces no client.
await createFromRoot(rootNodeFromAnchor(idl)).accept(
  renderVisitor(staging, { deleteFolderBeforeRendering: true }),
);
rmSync(out, { recursive: true, force: true });
cpSync(join(staging, 'src', 'generated'), out, { recursive: true });
rmSync(staging, { recursive: true, force: true });

/**
 * Drop the generated PLUGIN module and write our own index.
 *
 * `programs/arena.ts` is a Kit **8** plugin client (`ExtendedClient`, an RPC
 * shape from @solana/program-client-core). The app is on Kit 6 because that is
 * what the verified MWA payment path uses, and upgrading it two weeks before a
 * deadline to gain a convenience wrapper is a bad trade. The parts we actually
 * need — instruction builders, account decoders, PDA finders, error codes —
 * are version-agnostic codec code and compile against Kit 6 unchanged.
 *
 * The index is written by hand for a second reason: the account `Vote` and the
 * instruction `vote` both generate VOTE_DISCRIMINATOR, so a blanket re-export
 * of both is ambiguous.
 */
// Replace the generated PLUGIN module with the one constant the rest of the
// client needs from it.
//
// `programs/arena.ts` is a Kit **8** plugin client (`ExtendedClient`, an RPC
// shape from @solana/program-client-core). The app is on Kit 6 because that is
// what the verified MWA payment path uses, and upgrading it two weeks before a
// deadline to gain a convenience wrapper is a bad trade. Everything else the
// renderer emits — instruction builders, account decoders, PDA finders, error
// codes — is version-agnostic codec code that compiles against Kit 6 unchanged,
// and all of it imports exactly one symbol from here.
const programAddress = readFileSync(join(out, 'programs', 'arena.ts'), 'utf8').match(
  /ARENA_PROGRAM_ADDRESS\s*=\s*['"]([1-9A-HJ-NP-Za-km-z]+)['"]/,
)?.[1];
if (!programAddress) throw new Error('could not read ARENA_PROGRAM_ADDRESS from the generated plugin');
writeFileSync(
  join(out, 'programs', 'index.ts'),
  `// Generated by scripts/codegen.mjs — do not edit.\n` +
    `import { address, type Address } from '@solana/kit';\n\n` +
    `export const ARENA_PROGRAM_ADDRESS = address('${programAddress}') as Address<'${programAddress}'>;\n`,
);
rmSync(join(out, 'programs', 'arena.ts'), { force: true });

// The index is written by hand for a second reason: the account `Vote` and the
// instruction `vote` both generate VOTE_DISCRIMINATOR, so a blanket re-export
// of both is ambiguous.
writeFileSync(
  join(out, 'index.ts'),
  `// Generated by scripts/codegen.mjs — do not edit.\n` +
    `// The Kit-8 plugin module is deliberately not generated; see codegen.mjs.\n` +
    `export * from './accounts';\n` +
    `export * from './errors';\n` +
    `export * from './pdas';\n` +
    `export { ARENA_PROGRAM_ADDRESS } from './programs';\n` +
    `export {\n` +
    `  getCreateRoundInstruction,\n  getEnterInstruction,\n  getVoteInstruction,\n  getClaimPlaceInstruction,\n` +
    `} from './instructions';\n`,
);

console.log(`arena client -> ${out}`);
